name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        AWS_ACCES_KEY: ${{ secrets.AWS_ACCES_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
